### PR TITLE
Add callback after animation

### PR DESCRIPTION
**Pull request by lucas-aragno**
hey @bySabi ! 

I needed to run a callback after the animation on my project and I think that'd be a cool funcionality for the library let me know what you think!

### CODE REVIEW

**Comment by bySabi** [comment]
Hi @lucas-aragno, thanks for the PR, any contributing is welcome.

I really open to extend this component. I guest you need update some states when scroll happends. But your PR make two things that I prefer avoid if we have a better solution, opinionated here. One is the need to add a new `prop` and the other is fact that `callback after` is the half of use case, what happends with `before animation`
What you think is we extend `animate` prop API with: `beforeHook`  and  `afterHook` callbacks?
Your use case will be, for Ex:

```
<Scrollchor to="#aboutus" animate={{afterHook: (event) => updateState()}} className="nav-link">Home</Scrollchor>
```

**Comment by bySabi** [comment]
I push `beforeHook` and `afterHook` on master, currently unpublished. 
Let me see what you think ...

I don´t sure is more "semantic" correct put callbacks on `animate` object or create separate props like, maybe: `onBeforeAnimate` , `onAfterAnimate` or what ever ...

**Comment by lucas-aragno** [comment]
hey @bySabi sorry for the late response, have been really busy this couple of weeks. I think those hooks are exactly what I need 😄 , Thank you. I'll close this issue now

**Comment by bySabi** [comment]
@lucas-aragno at the I add two new props... `beforeAnimate` and `afterAnimate` callbacks ... 
It is already published on `2.2.0` , tell me  if it´s right for you.

**Pull request closed without merging**
