### PR TITLE
#9 implemented: fixed cross-browser compatibility, added propType

### PR DESCRIPTION
**Pull request by xehpuk**
Test repo: https://github.com/xehpuk/react-scrollchor/tree/target-example

### CODE REVIEW

**Comment by bySabi** [comment]
Great!!!

**Comment by bySabi** [comment]
Please PR branch `target-example` to branch: https://github.com/bySabi/react-scrollchor/tree/example

**Comment by xehpuk** [comment]
It seems like it's not possible to create a pull request to a new upstream branch: https://stackoverflow.com/questions/9796370/github-pull-request-to-a-new-upstream-branch
And if I PR to `example`, the old example would be gone.

**Comment by bySabi** [comment]
React-scrollchor is now in a organization and your are invited to join.

Now you can merge your PR, I hope

**Comment by bySabi** [comment]
Still we are in time of change Organization name.

Open to propositions ...

**Comment by xehpuk** [comment]
When trying to push the new branch to the repo, I get this error:

> remote: Permission to some-react-components/react-scrollchor.git denied to xehpuk.
fatal: unable to access 'https://github.com/some-react-components/react-scrollchor.git/': The requested URL returned error: 403

I'm not very knowledgeable in the workings of GitHub. Do you have any idea why this happens?

**Comment by bySabi** [comment]
Now your are owner like me of "some-react-component" Orgz.

Try again and feel free to make the change you wish.

**Comment by xehpuk** [comment]
Now it works. 👍
TODO: update the `README`

**Pull request merged**
